name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
      docker build -f Dockerfile . --tag frps-client:$(date +%s)
      docker build -f Dockerfile.build . --tag frps-server:$(date +%s)